export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const GET_SUBJECTS = 'GET_SUBJECTS';
export const SUBJECT_ERROR = 'SUBJECT_ERROR';
export const GET_BASE_TEST_QUESTIONS = 'GET_BASE_TEST_QUESTIONS';
export const GET_TEST_QUESTION = 'GET_TEST_QUESTION';
export const BASE_QUESTION_ERROR = 'BASE_QUESTION_ERROR'
export const QUESTION_ERROR = 'QUESTION_ERROR';
export const GET_TESTS = 'GET_TESTS';
export const TEST_ERROR = 'TEST_ERROR';
export const GET_TEST_SUBJECTS = 'GET_TEST_SUBJECTS';
export const POST_ANSWERS = 'POST_ANSWERS';
export const POST_BASE_ANSWERS = 'POST_BASE_ANSWERS';
export const ANSWERS_ERROR = 'ANSWERS_ERROR';
export const QUESTION_RANK = 'QUESTION_RANK';




